<?xml version="1.0" encoding="utf-8"?><testsuite errors="0" failures="1" name="pytest" skips="0" tests="1" time="6.734"><testcase classname="scripts.FileUpload.CheckFileUpload" name="test_local_upload" time="3.3599011898"><failure message="test failure">Traceback (most recent call last):
  File &quot;/Users/adam/work/saunter/py.saunter-examples/picpaste/webdriver/scripts/FileUpload.py&quot;, line 17, in test_local_upload
    preview = self.u.upload(&apos;english_muffin.jpg&apos;)
  File &quot;/Users/adam/work/saunter/py.saunter-examples/picpaste/webdriver/modules/pages/upload.py&quot;, line 47, in upload
    path_to_image = os.path.join(self.config.get(&apos;Saunter&apos;, &apos;base&apos;), &apos;support&apos;, &apos;files&apos;, image)
AttributeError: &apos;ConfigWrapper&apos; object has no attribute &apos;get&apos;</failure></testcase></testsuite>