<?xml version="1.0" encoding="utf-8"?><testsuite errors="0" failures="1" name="" skips="0" tests="1" time="13.400"><testcase classname="scripts.FileUpload.CheckFileUpload" name="test_local_upload" time="0.303605079651"><failure message="test failure">Traceback (most recent call last):
  File &quot;/Users/adam/work/saunter/py.saunter-examples/picpaste/conftest.py&quot;, line 31, in pytest_runtest_call
    raise(e)
NameError: global name &apos;os&apos; is not defined</failure></testcase></testsuite>