<?xml version="1.0" encoding="utf-8"?><testsuite errors="0" failures="1" name="" skips="0" tests="1" time="11.766"><testcase classname="scripts.FileUpload.CheckFileUpload" name="test_local_upload" time="0.513839006424"><failure message="test failure">Traceback (most recent call last):
  File &quot;/Users/adam/work/saunter/py.saunter-examples/picpaste/rc/conftest.py&quot;, line 32, in pytest_runtest_call
    raise(e)
NameError: global name &apos;selenium&apos; is not defined</failure></testcase></testsuite>