<?xml version="1.0" encoding="utf-8"?><testsuite errors="0" failures="1" name="" skips="0" tests="1" time="16.874"><testcase classname="scripts.FileUpload.CheckFileUpload" name="test_local_upload" time="0.79577589035"><failure message="test failure">Traceback (most recent call last):
  File &quot;/Users/adam/work/saunter/py.saunter-examples/picpaste/webdriver/conftest.py&quot;, line 32, in pytest_runtest_call
    raise(e)
AttributeError: &apos;CheckFileUpload&apos; object has no attribute &apos;u&apos;</failure><system-out>
[[ATTACHMENT|/Users/adam/work/saunter/py.saunter-examples/picpaste/webdriver/logs/2013-05-28-21-38-55/CheckFileUpload/test_local_upload/exception.png]]
</system-out></testcase></testsuite>